### ISSUE TITLE
Error while installing on Mac

### ISSUE THREAD

**Issue by knc6** [usnistgov/cdcs-docker#14]
We installed Docker desktop for Mac. While following the instructions on README, we found error complaining about apt-get command not found. Is there any separate instruction for Mac installation?

**Comment by Guillaume-sousa** [comment]
No separate instructions for Mac. Please check the value that is set in the `build/.env` file for `PYTHON_VERSION`. It needs to be a base image that supports `apt-get`. Currently, we have `PYTHON_VERSION=3.7-slim-buster` which is a Debian where the `apt-get` command is available.

**Comment by markkasule** [comment]
Here is a screenshot of the values that look correctly set after running the vim .env in build directory
![Screen Shot 2022-02-09 at 12 49 20 PM](https://user-images.githubusercontent.com/31680529/153260891-70474312-aeb8-4104-a917-a3eec0819228.png)
s

Here is the error returned: 
docker-compose build --no-cache

ERROR [ 2/15] RUN apt-get update && apt-get install -y     netcat vim python curl git dnsu

Note: I use homebrew and I do not think the apt-get command works on Mac.

I tried to install the packages in question "netcat, curl" using brew but the error still persisted.

**Comment by Guillaume-sousa** [comment]
The `apt-get` is executed in the context of the docker image (which is a Debian Buster, that comes with `apt-get`), and not on the Mac directly. Installing those packages on your Mac directly with homebrew will not be helpful. 
I am working on a Mac too, and never had this issue. Would you mind pasting here the portion of the `docker-compose build --no-cache` output, where the error occurs. 
Thank you.

**Comment by Guillaume-sousa** [comment]
Seems that the issue is coming from the fact that the CDCS image was being built on a Mac with a M1 chip (Arm-based architecture), and that the `lib32z1-dev` package does not seem to be compatible with this type of architecture, thus producing the following error: `Unable to locate package lib32z1-dev`.
